### ISSUE TITLE
virtual_camera_monoでvirtual_camera_frameが出力されない

### ISSUE THREAD

**Issue by shmpwk** [shmpwk/grasp_recognition#4]
[virtual_camera_mono](https://jsk-recognition.readthedocs.io/en/latest/jsk_perception/nodes/virtual_camera_mono.html)のサンプルをそのまま真似して[このよう](https://github.com/shmpwk/grasp_recognition/blob/master/launch/virtual_camera_mono.launch)に作りました。
しかし、以下の写真のようにvirtual camera monoのimageとtfが出力されていません。
![Screenshot from 2020-09-28 17-25-31](https://user-images.githubusercontent.com/42209144/94408352-a2f80580-01af-11eb-95e8-2ee453efabf2.png)

```
$ rostopic hz /virtual_camera_mono/image 
subscribed to [/virtual_camera_mono/image]
no new messages
no new messages
no new messages
no new messages
```
virtual cameraに関するframeも出力されていません。
```
rosrun tf view_frame
```
![Screenshot from 2020-09-28 17-27-22](https://user-images.githubusercontent.com/42209144/94408584-ef434580-01af-11eb-8574-0ae8cac8d01f.png)

**Comment by kosuke55** [comment]
sampleは動きますか？僕もmasterの最新版の`sample_virtual_camera_mono.launch`を試しましたがvirtual camera monoのimage見れました。

**Comment by shmpwk** [comment]
> sampleは動きますか？僕もmasterの最新版のsample_virtual_camera_mono.launchを試しましたがvirtual camera monoのimage見れました。

はい、僕もimageはみれました。しかし、作られたはずのtf(dummy_frameやvirtual_camera_frame)は見えないです

**Comment by shmpwk** [comment]
すみません、先程はたまたまゾンビプロセスのおかげでimageができていたようで、今改めて実行したらissueと同様の状態になっていましました。
初歩的な質問なのですが、サンプルのsample_virtual_camera_mono.launchを試すとき、rosbagは自分で用意するということであっていますでしょうか。自分が今試したのは、手元のxtionで適当にrosbagをとったものでした。

**Comment by kosuke55** [comment]
いや、サンプルのrosbagを使います。特にlaunchを書き換える必要はありません。
build時に自動でダウンロードされているはずです。
https://github.com/jsk-ros-pkg/jsk_recognition/blob/62aa2affa5ff82ab323f9ac7d1dfb48c43a5bcda/jsk_pcl_ros/CMakeLists.txt#L470-L471
今回の場合は以下のスクリプトで`stereo_arc2017_objects.bag`というものがダウンロードされてそれが使われてるはずです。
https://github.com/jsk-ros-pkg/jsk_recognition/blob/62aa2affa5ff82ab323f9ac7d1dfb48c43a5bcda/jsk_pcl_ros/scripts/install_sample_data.py#L61-L65

**Comment by shmpwk** [comment]
ありがとうございます。新しくワークスペースを作成してビルドした方にrosbagが見つかりました。
ただ、例えば`roslaunch jsk_perception sample_virtual_camera_mono.launch`を実行するときに、ビルドしたワークスペースで`source ~/WORKSPACE/devel/setup.bash`してもjsk_perceptionの参照先が、aptで入っている方
```
$ rospack find jsk_perception
/opt/ros/melodic/share/jsk_perception
```
しか参照されず、そこには所望のrosbagがないのでエラーが出てしまいます。どのようにしてビルドしたパッケージを参照できるのでしょうか。

**Comment by shmpwk** [comment]
すみません、一つ上の問題ですが解決できました。お騒がせしました。
sample_virtual_camera_mono.launchは問題なくimageやtfをrviz上で表示できました。

**Comment by kosuke55** [comment]
良かったです。他の人が同じ問題に躓いたときに対処できるように、
https://github.com/jsk-ros-pkg/jsk_recognition/issues/2530
に問題とその解決方法をまとめましょう。

**Comment by shmpwk** [comment]
何度もありがとうございます。
サンプルを動かすことはできましたが、[#issue2530](https://github.com/jsk-ros-pkg/jsk_recognition/issues/2530)の趣旨がサンプルを真似した[こちら](https://github.com/shmpwk/grasp_recognition/blob/master/launch/virtual_camera_mono.launch)でimageとtfが表示されていないことなので、そちらがうまくいきましたら書きます。

**Comment by kosuke55** [comment]
rosbagとその再生方法の情報が欲しいです。
use_sim_time を trueにして、rosbag play に--clockをつけてますか？

**Comment by shmpwk** [comment]
[こちら](https://drive.google.com/file/d/14SVE9uvNoY_r_8hnTq6FqXv2rqQJekck/view?usp=sharing)にrosbagをおきました。
```
$ roslaunch grasp_recognition virtual_camera_mono.launch 
```
を立ち上げた後、
```
$ rosparam set use_sim_time true
$ rosbag play fail_virtual_camera_mono.bag -l --clock 
```
でrosbagを再生します。

**Comment by kosuke55** [comment]
https://github.com/shmpwk/grasp_recognition/blob/36bdd1e9d9a99382f52b9e722ac1ce5d222a5434/launch/virtual_camera_mono.launch#L10-L11
from のtopic名の`~`を消してみてください。`~`の意味を調べておくと良いです。
![Screenshot from 2020-09-30 19-37-01](https://user-images.githubusercontent.com/39142679/94675339-86490280-0354-11eb-88eb-835644348ff0.png)

**Comment by shmpwk** [comment]
なるほどですね，，，理解が浅かったです．

こちらのjsk_recognitionのissue
https://github.com/jsk-ros-pkg/jsk_recognition/issues/2530
にも書きます。

ご丁寧にサポートありがとうございました！
